version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: local_postgres_build
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short_next
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_build:/var/lib/postgresql/data

  builder:
    build:
      context: .
      target: builder
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/short_next
      NODE_ENV: production
    command: sh -c "npx prisma generate && npm run build"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app

  app:
    build:
      context: .
      target: runner
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/short_next
      NODE_ENV: production
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - /app/.next
      - /app/node_modules
      - /app/public
    working_dir: /app
    command: ["node", "server.js"]

volumes:
  postgres_data_build:
