version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: pnpm dev
volumes:
  postgres_data:
