version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: local_postgres_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  # Different port for production
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  app:
    build: 
      context: .
      target: production
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      NODE_ENV: production
    ports:
      - "3001:3000"  # Different port for production
    restart: unless-stopped

volumes:
  postgres_data_prod:
